[package]
name = "rs-bytes2bzip2"
version = "0.1.0"
edition = "2021"

[dependencies.bzip2]
version = "0.4.4"

[dependencies.prost]
version = "0.11.9"

[dependencies.tonic]
version = "0.9.2"

[dependencies.tonic-web]
version = "0.9.2"

[dependencies.tokio]
version = "1"
features = ["rt-multi-thread"]

[build-dependencies.tonic-build]
version = "0.9.2"

