[package]
name = "rs-helper"
version = "0.1.0"
edition = "2021"

[dependencies.prost]
version = "0.11.9"

[dependencies.prost-types]
version = "0.11.9"

[dependencies.tonic]
version = "0.9.2"

[dependencies.tokio]
version = "1"
features = ["rt-multi-thread"]

[dependencies.tokio-stream]
version = "0.1"
features = [
	"net",
]

[dependencies.tower]
version = "0.4"

[dependencies.hyper]
version = "0.14"

[build-dependencies.tonic-build]
version = "0.9.2"
